#!/bin/bash

if ! [ -x "$(command -v docker)" ]; then
  curl -fsSL https://get.docker.com/ | sh 
  sudo systemctl enable docker
  sudo systemctl start docker
  
fi

export IMG=docker-jenkins-img
export CNT=docker-jenkins-cnt

sudo docker build -t $IMG -f Dockerfile .

sudo docker rm -f $CNT

sudo docker run -d -e JENKINS_OPTS=" --httpPort=8000" \
   --name $CNT \
   -p 8000:8000 \
   -v jerkins_home:/var/jenkins_home \
   $IMG
